import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import { parseCSV,parseDate,autoMapping,validateImport,MAX_IMPORT } from '../lib/import-data';
import { readSpreadsheet } from '../lib/read-spreadsheet';
import { GET,POST } from '../app/api/workspace/route';
import { dueDate,initialData,situation,today,addDays,validDate } from '../lib/domain';
let passed=0;
function ok(test:boolean,message:string){assert.ok(test,message);passed++;console.log('OK',message);}
const base=initialData().rules[0];
ok(dueDate('2026-09-25',{...base,days:1,mode:'uteis'})==='2026-09-28','Dia útil após sexta-feira');
ok(dueDate('2026-09-25',{...base,days:1,mode:'uteis'},['2026-09-28'])==='2026-09-29','Feriado excluído da contagem');
ok(dueDate('2026-12-31',{...base,days:1})==='2027-01-01','Virada de ano em dias corridos');
ok(dueDate('2028-02-28',{...base,days:1})==='2028-02-29','Ano bissexto');
ok(dueDate('2026-09-25',{...base,days:0})==='2026-09-25','Prazo zero');
ok(!validDate('2026-02-30'),'Data impossível rejeitada');
let state:any=await (await GET(new Request('http://localhost/api/workspace'))).json();
async function post(op:string,payload:any,version=state.version){const res=await POST(new Request('http://localhost/api/workspace',{method:'POST',headers:{'content-type':'application/json','origin':'http://localhost'},body:JSON.stringify({op,payload,version})}));const result:any=await res.json();if(res.ok)state=result;return {res,result};}
const fields={postureId:base.id,sql:'001.002.0003-4',address:'Endereço de teste',priority:'Alta',status:'Em acompanhamento',demand:'TESTE-001',sei:'SEI-001',notes:'Vistoria inicial',inspector:'Fiscal teste',date:today()};
ok((await post('action',fields)).res.status===400,'Postura não validada bloqueia cadastro');
ok((await post('rule',{...base,days:5})).res.ok,'Configuração de postura');
ok((await post('action',fields)).res.ok,'Cadastro de demanda');
const id=state.actions[0].id;
ok((await post('action',fields)).res.status===400,'Demanda duplicada rejeitada');
ok((await post('action',{...fields,id,address:'Endereço editado'})).res.ok,'Edição da demanda');
ok(state.actions[0].visits.length===1&&state.audit[0].before.address==='Endereço de teste','Auditoria preserva valores anteriores');
ok((await post('action',{...fields,demand:'FUTURA',date:addDays(today(),1)})).res.status===400,'Vistoria futura rejeitada');
const oldDue=state.actions[0].visits[0].due;
await post('rule',{...base,days:10});
ok(state.actions[0].visits[0].due===oldDue,'Mudança de regra preserva prazo anterior');
ok((await post('visit',{id,date:today(),note:'Retorno realizado',inspector:'Fiscal teste',status:'Aguardando retorno',postureId:base.id})).res.ok,'Nova vistoria');
ok(state.actions[0].visits.length===2&&state.actions[0].visits[0].rule.days===5&&state.actions[0].visits[1].rule.days===10,'Histórico e regras versionadas por vistoria');
const a=state.actions[0],due=a.visits[1].due;
ok(situation(a,due)==='Retorno hoje'&&situation(a,addDays(due,1))==='Retorno atrasado'&&situation(a,addDays(due,-1))==='Atenção'&&situation(a,addDays(due,-6))==='No prazo','Quatro situações de prazo');
ok(situation({...a,status:'Suspenso'},due)==='Sem retorno ativo','Suspensos não geram alertas');
ok((await post('holidays',{dates:['2026-12-25','2026-12-25']})).res.ok&&state.holidays.length===1,'Feriados persistidos e sem duplicação');
ok((await post('read',{keys:['teste']})).res.ok&&state.read.local.includes('teste'),'Leitura de notificações persistida');
ok((await post('read',{keys:[]},0)).res.status===409,'Conflito de edição rejeitado');
const reload:any=await (await GET(new Request('http://localhost/api/workspace'))).json();
ok(reload.actions[0].id===id&&reload.actions[0].visits.length===2,'Persistência após nova leitura');
ok((await post('delete',{id})).res.ok&&state.actions[0].deleted&&state.audit[0].before.visits.length===2,'Exclusão preserva histórico em auditoria');
ok((await post('rule',{...base,active:false})).res.ok&&!state.rules[0].active,'Desativação de postura');
ok((await post('action',{...fields,demand:'OUTRA'})).res.status===400,'Postura inativa bloqueia novo cadastro');
const csv=parseCSV('\uFEFFDemanda;Endereço;Obs\r\n001;"Rua A; 20";"Primeira linha\nsegunda ""aspas"""\r\n');
ok(csv.length===2&&csv[1][0]==='001'&&csv[1][1]==='Rua A; 20'&&csv[1][2]==='Primeira linha\nsegunda "aspas"','CSV preserva zeros, separadores, quebras e aspas');
ok(parseCSV('a,b\n1,2')[1][1]==='2'&&parseCSV('a\tb\n1\t2')[1][1]==='2','CSV aceita vírgula e tabulação');
ok(parseDate('5/9/2026')==='2026-09-05'&&!parseDate('31/02/2026'),'Datas brasileiras validadas');
ok(autoMapping(['Nº da demanda','Endereço','Data da última vistoria']).date===2,'Mapeamento reconhece cabeçalhos em português');
await post('rule',{...base,active:true});
const input={posture:base.name,demand:'IMPORT-001',address:'Endereço importado',date:today(),inspector:'Fiscal importação',sql:'0001',sei:'00002',priority:'',status:'',notes:'Observação importada'};
const importBefore=state.actions.length;
const response=await post('import',{source:'arquivo.csv',rows:[{line:2,input},{line:3,input:{...input,demand:'IMPORT-002',address:''}}]});
ok(response.res.status===400&&(await (await GET(new Request('http://localhost/api/workspace'))).json() as any).actions.length===importBefore,'Importação inválida não grava nenhuma linha');
const result=await post('import',{source:'arquivo.csv',rows:[{line:2,input},{line:3,input:{...input,demand:'IMPORT-002'}}]});
ok(result.res.ok&&state.actions.length===importBefore+2,'Importação em lote persiste todas as linhas válidas');
ok(state.actions.at(-1).priority==='Média'&&state.actions.at(-1).status==='Em acompanhamento','Campos opcionais recebem padrões documentados');
ok(state.audit[1].after.importacao.arquivo==='arquivo.csv'&&state.audit[1].after.importacao.linha===3,'Auditoria guarda arquivo, linha e lote');
ok((await post('import',{source:'repetido.csv',rows:[{line:2,input}]})).res.status===400,'Reimportação não duplica demanda existente');
ok(validateImport([{line:2,input:{...input,demand:'NOVA'}},{line:3,input:{...input,demand:'NOVA'}}],state)[1].errors.length>0,'Prévia identifica duplicidade dentro do arquivo');
ok(validateImport([{line:2,input:{...input,demand:'NOVA',address:'[FÓRMULA: substitua pelo valor]'}}],state)[0].errors.length>0,'Fórmulas não são cadastradas como valores');
ok((await post('import',{source:'grande.csv',rows:Array.from({length:MAX_IMPORT+1},(_,i)=>({line:i+2,input:{...input,demand:'LOTE-'+i}}))})).res.status===400,'Limite de lote também é validado no servidor');
const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Demandas');ws.addRow(['Nº da demanda','SQL','Data da última vistoria','Endereço']);ws.addRow(['001',23,new Date('2026-09-20T00:00:00Z'),'Rua de teste']);ws.getCell('B2').numFmt='00000';
const xlsx=await wb.xlsx.writeBuffer();const parsed=await readSpreadsheet(new File([xlsx as any],'teste.xlsx'));
ok(parsed[0].name==='Demandas'&&parsed[0].rows[1][1]==='00023'&&parsed[0].rows[1][2]==='2026-09-20','Excel real: aba, identificadores formatados e datas');
const csvParsed=await readSpreadsheet(new File(['Demanda;Endereço\n001;Rua Teste'],'teste.csv'));
ok(csvParsed[0].rows[1][0]==='001','Leitura de arquivo CSV real');
console.log(`\n${passed} verificações passaram.`);
