import assert from 'node:assert/strict';
import { GET,POST } from '../app/api/workspace/route';
import { dueDate,initialData,situation,today,addDays,validDate } from '../lib/domain';
let passed=0;
function ok(test:boolean,message:string){assert.ok(test,message);passed++;console.log('OK',message);}
const base=initialData().rules[0];
ok(dueDate('2026-09-25',{...base,days:1,mode:'uteis'})==='2026-09-28','Dia útil após sexta-feira');
ok(dueDate('2026-09-25',{...base,days:1,mode:'uteis'},['2026-09-28'])==='2026-09-29','Feriado excluído da contagem');
ok(dueDate('2026-12-31',{...base,days:1})==='2027-01-01','Virada de ano em dias corridos');
ok(dueDate('2028-02-28',{...base,days:1})==='2028-02-29','Ano bissexto');
ok(dueDate('2026-09-25',{...base,days:0})==='2026-09-25','Prazo zero');
ok(!validDate('2026-02-30'),'Data impossível rejeitada');
let state:any=await (await GET(new Request('http://localhost/api/workspace'))).json();
async function post(op:string,payload:any,version=state.version){const res=await POST(new Request('http://localhost/api/workspace',{method:'POST',headers:{'content-type':'application/json','origin':'http://localhost'},body:JSON.stringify({op,payload,version})}));const result:any=await res.json();if(res.ok)state=result;return {res,result};}
const fields={postureId:base.id,sql:'001.002.0003-4',address:'Endereço de teste',priority:'Alta',status:'Em acompanhamento',demand:'TESTE-001',sei:'SEI-001',notes:'Vistoria inicial',inspector:'Fiscal teste',date:today()};
ok((await post('action',fields)).res.status===400,'Postura não validada bloqueia cadastro');
ok((await post('rule',{...base,days:5})).res.ok,'Configuração de postura');
ok((await post('action',fields)).res.ok,'Cadastro de demanda');
const id=state.actions[0].id;
ok((await post('action',fields)).res.status===400,'Demanda duplicada rejeitada');
ok((await post('action',{...fields,id,address:'Endereço editado'})).res.ok,'Edição da demanda');
ok(state.actions[0].visits.length===1&&state.audit[0].before.address==='Endereço de teste','Auditoria preserva valores anteriores');
ok((await post('action',{...fields,demand:'FUTURA',date:addDays(today(),1)})).res.status===400,'Vistoria futura rejeitada');
const oldDue=state.actions[0].visits[0].due;
await post('rule',{...base,days:10});
ok(state.actions[0].visits[0].due===oldDue,'Mudança de regra preserva prazo anterior');
ok((await post('visit',{id,date:today(),note:'Retorno realizado',inspector:'Fiscal teste',status:'Aguardando retorno',postureId:base.id})).res.ok,'Nova vistoria');
ok(state.actions[0].visits.length===2&&state.actions[0].visits[0].rule.days===5&&state.actions[0].visits[1].rule.days===10,'Histórico e regras versionadas por vistoria');
const a=state.actions[0],due=a.visits[1].due;
ok(situation(a,due)==='Retorno hoje'&&situation(a,addDays(due,1))==='Retorno atrasado'&&situation(a,addDays(due,-1))==='Atenção'&&situation(a,addDays(due,-6))==='No prazo','Quatro situações de prazo');
ok(situation({...a,status:'Suspenso'},due)==='Sem retorno ativo','Suspensos não geram alertas');
ok((await post('holidays',{dates:['2026-12-25','2026-12-25']})).res.ok&&state.holidays.length===1,'Feriados persistidos e sem duplicação');
ok((await post('read',{keys:['teste']})).res.ok&&state.read.local.includes('teste'),'Leitura de notificações persistida');
ok((await post('read',{keys:[]},0)).res.status===409,'Conflito de edição rejeitado');
const reload:any=await (await GET(new Request('http://localhost/api/workspace'))).json();
ok(reload.actions[0].id===id&&reload.actions[0].visits.length===2,'Persistência após nova leitura');
ok((await post('delete',{id})).res.ok&&state.actions[0].deleted&&state.audit[0].before.visits.length===2,'Exclusão preserva histórico em auditoria');
ok((await post('rule',{...base,active:false})).res.ok&&!state.rules[0].active,'Desativação de postura');
ok((await post('action',{...fields,demand:'OUTRA'})).res.status===400,'Postura inativa bloqueia novo cadastro');
console.log(`\n${passed} verificações passaram.`);
