'use client';
import { useState,type ChangeEvent } from 'react';
import { Upload,FileSpreadsheet,ArrowDownToLine,CheckCircle2,AlertCircle } from 'lucide-react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { importFields,autoMapping,validateImport,MAX_IMPORT,type ImportField,type ImportInput,type ImportRow } from '@/lib/import-data';
import { readSpreadsheet,type SheetData } from '@/lib/read-spreadsheet';
import { dueDate,formatDate,today,type Data } from '@/lib/domain';
type Props={data:Data;busy:boolean;onClose:()=>void;onImport:(rows:ImportRow[],source:string)=>Promise<boolean>};
function saveCSV(name:string,rows:string[][]){const body='\uFEFF'+rows.map(r=>r.map(v=>'"'+(/^[=+\-@\t\r]/.test(v)?"'":'')+v.replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([body],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function ImportDialog({data,busy,onClose,onImport}:Props){
 const [sheets,setSheets]=useState<SheetData[]>([]),[sheetIndex,setSheetIndex]=useState('0'),[filename,setFilename]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[mapping,setMapping]=useState<Record<ImportField,number>>(autoMapping([])),[defaults,setDefaults]=useState({posture:'',inspector:'',date:''}),[step,setStep]=useState<'map'|'preview'>('map');
 const sheet=sheets[Number(sheetIndex)],headers=sheet?.rows[0]||[];
 function chooseSheet(index:string,list=sheets){setSheetIndex(index);setMapping(autoMapping(list[Number(index)]?.rows[0]||[]));setStep('map');setError('');}
 async function selectFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setLoading(true);setError('');setSheets([]);setFilename(file.name);setStep('map');try{const results=await readSpreadsheet(file);if(!results.length||results.every(s=>!s.rows.length))throw Error('A planilha está vazia.');setSheets(results);chooseSheet('0',results);}catch(e){setError(e instanceof Error?e.message:'Não foi possível ler o arquivo.');}finally{setLoading(false);}}
 const rows:ImportRow[]=(sheet?.rows.slice(1)||[]).map((cells,i)=>({line:i+2,input:Object.fromEntries(importFields.map(([key])=>[key,mapping[key]>=0?cells[mapping[key]]||'':''])) as ImportInput})).filter((r,i)=>sheet!.rows[i+1].some(cell=>cell.trim())).map(r=>({...r,input:{...r.input,posture:r.input.posture.trim()||defaults.posture,inspector:r.input.inspector.trim()||defaults.inspector,date:r.input.date.trim()||defaults.date}}));
 const results=validateImport(rows,data),valid=results.filter(r=>!r.errors.length),invalid=results.filter(r=>r.errors.length);
 const ready=rows.length>0&&rows.length<=MAX_IMPORT;
 async function confirm(){setError('');const ok=await onImport(valid.map(r=>({line:r.line,input:r.input})),filename+' · '+sheet.name);if(ok)onClose();else setError('A importação não foi salva. Confira o aviso e tente novamente. Os dados da prévia foram preservados.');}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy&&!loading)onClose();}}><DialogContent className="import-dialog" showCloseButton={!busy&&!loading}><DialogHeader><DialogTitle>Importar demandas</DialogTitle><DialogDescription>Traga os registros de uma planilha para a sua fiscalização.</DialogDescription></DialogHeader>
 <div className="import-steps"><span className={step==='map'?'current':''}>1. Arquivo e colunas</span><span className={step==='preview'?'current':''}>2. Conferir e importar</span></div>
 {step==='map'?<><div className="import-upload"><FileSpreadsheet size={28}/><div><strong>Excel (.xlsx) ou CSV</strong><p>Cabeçalho na primeira linha · até {MAX_IMPORT} demandas · máximo 5 MB</p><input type="file" accept=".xlsx,.csv" aria-label="Selecionar planilha" disabled={loading||busy} onChange={selectFile}/></div></div><button className="text-btn" onClick={()=>saveCSV('modelo-importacao-fiscaliza.csv',[importFields.map(([,label])=>label)])}><ArrowDownToLine size={15}/>Baixar modelo CSV</button>
 {loading&&<p role="status">Lendo a planilha…</p>}
 {sheet&&<><div className="import-file"><span>{filename}</span><Select value={sheetIndex} onValueChange={chooseSheet}><SelectTrigger aria-label="Aba da planilha"><SelectValue/></SelectTrigger><SelectContent>{sheets.map((s,i)=><SelectItem value={String(i)} key={i}>{s.name}</SelectItem>)}</SelectContent></Select></div><h3>Associe as colunas</h3><p className="import-help">Confira as associações sugeridas. Colunas não selecionadas não serão importadas.</p><div className="import-mapping">{importFields.map(([key,label])=><div key={key}><label id={'map-'+key}>{label}{['posture','demand','address','date','inspector'].includes(key)?' *':''}</label><Select value={String(mapping[key])} onValueChange={v=>setMapping(m=>({...m,[key]:Number(v)}))}><SelectTrigger aria-labelledby={'map-'+key}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="-1">Não importar esta coluna</SelectItem>{headers.map((h,i)=><SelectItem value={String(i)} key={i}>{String(i+1).padStart(2,'0')} · {h||'Sem título'}</SelectItem>)}</SelectContent></Select></div>)}</div>
 <details className="import-defaults"><summary>Completar campos vazios</summary><p className="import-help">Estes valores serão usados somente onde a linha não tiver informação.</p><div className="import-default-grid"><label className="field"><span>Postura</span><Select value={defaults.posture||'none'} onValueChange={v=>setDefaults(d=>({...d,posture:v==='none'?'':v}))}><SelectTrigger aria-label="Postura para campos vazios"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Não preencher</SelectItem>{data.rules.filter(r=>r.active&&r.configured).map(r=><SelectItem key={r.id} value={r.name}>{r.name}</SelectItem>)}</SelectContent></Select></label><label className="field"><span>Fiscal</span><input value={defaults.inspector} maxLength={120} onChange={e=>setDefaults(d=>({...d,inspector:e.target.value}))}/></label><label className="field"><span>Data da vistoria</span><input type="date" max={today()} value={defaults.date} onChange={e=>setDefaults(d=>({...d,date:e.target.value}))}/></label></div></details>
 <p className="import-help">Prioridade vazia: Média. Status vazio: Em acompanhamento. Datas: DD/MM/AAAA ou AAAA-MM-DD. Formate identificadores como texto para preservar zeros à esquerda. Fórmulas devem ser convertidas em valores.</p></>}
 </>:<><div className="import-summary"><div><CheckCircle2 size={18}/><strong>{valid.length}</strong> prontas para importar</div><div><AlertCircle size={18}/><strong>{invalid.length}</strong> com pendências</div></div><p className="import-help">Somente as {valid.length} linhas válidas serão cadastradas. As {invalid.length} linhas com pendências serão ignoradas. Demandas existentes não serão alteradas. Os retornos serão calculados pelas regras atuais.</p><div className="table-shell import-preview"><Table><TableHeader><TableRow><TableHead>Linha</TableHead><TableHead>Demanda / endereço</TableHead><TableHead>Postura / fiscal</TableHead><TableHead>Vistoria / retorno</TableHead><TableHead>Prioridade / status</TableHead><TableHead>Validação</TableHead></TableRow></TableHeader><TableBody>{results.map(r=><TableRow key={r.line}><TableCell>{r.line}</TableCell><TableCell><strong>{r.payload.demand||'Sem número'}</strong><small>{r.payload.address||'Sem endereço'}</small></TableCell><TableCell>{r.input.posture||'Sem postura'}<small>{r.payload.inspector||'Sem fiscal'}</small></TableCell><TableCell>{formatDate(r.payload.date)}<small>{!r.errors.length?'Retorno: '+formatDate(dueDate(r.payload.date,data.rules.find(p=>p.id===r.payload.postureId)!,data.holidays)):'—'}</small></TableCell><TableCell>{r.payload.priority||'Inválida'}<small>{r.payload.status||'Inválido'}</small></TableCell><TableCell>{r.errors.length?<span className="import-problems">{r.errors.join(' ')}</span>:<span className="badge green">Pronta</span>}</TableCell></TableRow>)}</TableBody></Table></div>{invalid.length>0&&<button className="text-btn" onClick={()=>saveCSV('pendencias-importacao.csv',[['Linha',...importFields.map(([,label])=>label),'Pendências'],...invalid.map(r=>[String(r.line),...importFields.map(([key])=>r.input[key]),r.errors.join(' ')])])}><ArrowDownToLine size={15}/>Baixar linhas com pendências</button>}</>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 {sheet&&!rows.length&&<p className="form-error">Não há linhas com dados abaixo do cabeçalho.</p>}
 <div className="form-footer"><button className="btn" disabled={busy||loading} onClick={step==='preview'?()=>setStep('map'):onClose}>{step==='preview'?'Voltar às colunas':'Cancelar'}</button>{step==='map'?<button className="btn primary" disabled={!ready||loading} onClick={()=>{setError('');setStep('preview');}}>Conferir {rows.length} linhas</button>:<button className="btn primary" disabled={busy||!valid.length} onClick={confirm}><Upload size={16}/>{busy?'Importando…':`Importar ${valid.length} demandas`}</button>}</div>
 </DialogContent></Dialog>;
}
